---
id: sec-species
title: "Species representation"
abstract:
    Here the selection of species, occurrence data sources, conservation status, and species distributions are described.

author:
    - name: Paul Gordijn
      orcid: "0000-0002-0580-3107"
      affiliations:
        id: bspi
        name: Biodiversity, Spatial Planning and Information, Ezemvelo KZN Wildlife
    - name: Felicity Elliot
      affiliations:
        ref: bspi
    - name: Shannon Rushworth
      affiliations:
        ref: bspi
    - name: Andy Blackmore
      affiliations:
        id: iem
        name: Integrated Environmental Management & Protected Area Planning, Ezemvelo KZN Wildlife
    - name: Craig Mulqueeny
      affiliations:
        id: ss
        name: Scientific Services, Ezemvelo KZN Wildlife
    - name: Ian Rushworth
      affiliations:
        ref: ss
    - name: Adrian Armstrong
      affiliations:
        id: cra
        name: Scientific Services, Conservation and Research, Ezemvelo KZN Wildlife
    - name: Clinton Carbutt
      affiliations:
        ref: cra
    - name: Brent Coverdale
      affiliations:
        ref: cra
    - name: Debbie Jewitt
      affiliations:
        ref: cra
    - name: Skhumuzo Khubeka
      affiliations:
        ref: cra


title-block-banner: true
bibliography: refs/bspi.bib

execute: 
  warning: false
  message: false

# DOCX:
# To convert to word run the build word script
# cd website
# . scripts/build_word.sh
---

# Criteria for the selection of species {#sec-spp_crit}

## Introduction

The *broad-ranging* ecosystem representation is complemented by a *targeted* approach that focuses on specific species. The targeted approach required a systematic selection of species [@sanbi2024mbp-a]. Ezemvelo KZN Wildlife scientists and a broad range of stakeholders developed the criteria for the inclusion of species [@elliot2023bcp-a]. For the KwaZulu-Natal conservation plan, these criteria were applied to each group of taxa: [Amphibians](features_spp_amphibians.qmd), [Aquatic taxa](features_spp_aquatic.qmd), [Invertebrates](features_spp_invertebrates.qmd), [Mammals](features_spp_mammals.qmd), [Plants](features_spp_plants.qmd), and [Reptiles](features_spp_reptiles.qmd).

## Criteria for inclusion

```{r}
#| tbl-cap: "Criteria for inclusion of species in the targeted approach."
#| label: tbl-spp-criteria
#| echo: false
#| eval: true

# load packages
library(knitr)
library(kableExtra)
library(flextable)

criteria <- data.frame(
  ID = 1:12,
  Criteria = c(
    "Endemic to KwaZulu-Natal.",
    "Near Endemic to KwaZulu-Natal (50–99% of taxon distribution falls within KwaZulu-Natal).",
    "Threat status (CR, EN, Rare, VU, NT). Global or Regional. Highest threat status taken.",
    "International obligation.",
    "Umbrella species.",
    "Isolated from core known range with genetic differences.",
    "Edge of range species (may be well protected in KZN but globally/regionally threatened).",
    "Life‑history stage essential for protection of species.",
    "Species conservation plan or biodiversity management plan.",
    "Other (specify).",
    "Resource use threat.",
    "Specific populations (e.g., Tembe elephants, berg eland)."
  ),
  Rules = c(
    "Feature must be triggered by ≥1 criterion; criteria equal weighting; may include uncertain data but removed if insufficient; consider age and accuracy of data.",
    rep("", 11)
  )
)
# knitr::kable(criteria) # this is supposed to render for word whilst the kable_styling will not
tbl <- flextable(criteria) |> autofit()
tbl <- color(x = tbl, color = "#2e2828")
tbl

# kable(criteria
#       , label = "tbl-spp-criteria"
# 	) %>%
#   kable_styling(full_width = FALSE, bootstrap_options = c("striped","hover"))
```