---
id: intro
title: "Introduction"
abstract:
    The KwaZulu‑Natal terrestrial conservation plan is closely integrated with neighbouring conservation initiatives and seeks to connect multiple realms of biodiversity, from the marine to the terrestrial environment. Its overarching aim is to secure sufficient space for conservation while minimising constraints and maximising available opportunities. The following section outlines the conservation planning process and the rationale that underpins it.

author:
    - name: Paul Gordijn
      orcid: "0000-0002-0580-3107"
      affiliations:
        id: bspi
        name: Biodiversity, Spatial Planning and Information, Ezemvelo KZN Wildlife
    - name: Felicity Elliot
      affiliations:
        ref: bspi
    - name: Shannon Rushworth
      affiliations:
        ref: bspi
    - name: Andy Blackmore
      affiliations:
        id: iem
        name: Integrated Environmental Management & Protected Area Planning, Ezemvelo KZN Wildlife
    - name: Craig Mulqueeny
      affiliations:
        id: ss
        name: Scientific Services, Ezemvelo KZN Wildlife
    - name: Ian Rushworth
      affiliations:
        ref: ss
    - name: Adrian Armstrong
      affiliations:
        id: cra
        name: Scientific Services, Conservation and Research, Ezemvelo KZN Wildlife
    - name: Clinton Carbutt
      affiliations:
        ref: cra
    - name: Brent Coverdale
      affiliations:
        ref: cra
    - name: Debbie Jewitt
      affiliations:
        ref: cra
    - name: Skhumuzo Khubeka
      affiliations:
        ref: cra

bibliography: /home/paulg/refs/bspi.bib

execute: 
  warning: false
  message: false

# DOCX:
# To convert to word run the build word script
# cd website
# . scripts/build_word.sh
---

<!-- [Download Word (docx)](intro.docx){.btn .btn-secondary} -->

# The KwaZulu-Natal systematic conservation plan {#sec-updated-scp}

## Plan aim & stages {#sec-stages}

This terrestrial conservation plan aims to solve the problem of: how to ensure sufficient space for biodiversity conservation, in the KwaZulu-Natal terrestrial realm, whilst simultaneously minimising constraints and maximising opportunities (see @nte-cost). This is also known as the minimum set of protected areas' solution (i.e., the 'min set') [@margules2000scp; @hanson2025scp]. There are four broad stages that need to be addressed for resolution of this conservation problem [@escott2016dkn; @sanbi2024mbp] (@fig-flow_main).

::::{.column-margin}
::: {.callout-note #nte-cost title='Costs & decision support'}
Constraints and opportunities are referred as **costs** in conservation planning. These costs are more than the monetary value of acquiring protected areas for conservation efforts. In conservation planning 'costing' involves how complex socio-ecological factors are quantified and tradeoffs made. The balancing of these tradeoffs is the **'decision support'** mechanism that helps optimise the conservation planning solution *with* other human land use activities [@escott2016dkn; @sanbi2024mbp].
:::
::::

::: {#fig-flow_main}

```{mermaid}
%%| fig-align: center

%% png: images/intro/fig01.png

flowchart TD

%% === Main stages ===
obj1([1. Features: what & where])
%%obj2([Status assessment])
obj2([2. Representation & <br> persistence targets])
obj3([3. Decision support])
obj4([4. Prioritisation analysis])

%%obj1 --> obj2
obj1 --> obj2
obj2 --> obj3
obj3 --> obj4

%% Feedback (use dashed; if not supported, we’ll restyle via linkStyle)

%%obj3 -.-> obj2
obj2 -.-> obj1
obj3 -.-> obj2
obj4 -.-> obj3
```

The iterative stages, from gathering data, target setting, to prioritisation analyses, in conservation planning (c.f. @sanbi2024mbp). **(1)** The first stage addresses the what and where of biodiversity-related landscape features. **(2)** The second speaks to goal setting for the space biodiversity needs. **(3)** The third stage deals with setting up decision-making criteria that helps balance tradeoffs between the 'costs' of conservation efforts and socio-ecological factors (see @nte-cost). **(4)** Finally, the forth involves a robust and transparent analysis that solves the problem of the where and how should conservation efforts be prioritised at minimum 'cost'.
:::

The what and where of biodiversity-related features requires a collation and modelling of biodiversity occurrence data in order to provide the best possible spatial representation of biodiversity. This helps guarantee that conservation efforts are directed to the most appropriate locations. Other important what and where features for biodiversity include key habitat features for breeding, or safe zones (refugia).

The second stage concerns determination of meaningful representation and persistence targets. In other words, how much of which ecosystems and ecological features need to be represented, in the conservation plan, to secure the persistence of biodiversity. Setting up decision-support mechanisms helps us ensure that conservation efforts are focused on optimal locations. For this, other land uses and socio-ecological dynamics have to be considered [@margules2000scp; @hanson2025scp]. Once this data is gathered the final stage involves the prioritisation analysis. Multiple analyses are run showing different scenarios in a transparent process to demonstrate how the plan attempts to optimise conservation while supporting critical socio-ecological dynamics [@escott2016dkn; @sanbi2024mbp].

# Integrating biodiversity realms

Integrating the terrestrial conservation plan with the marine, estuarine, and freshwater biodiversity realms is critical for an overall *land- to sea-scape* approach. This integration ensures that critical marine realms are supported by important estuaries. These estuaries are supported by a freshwater plan, and conservation in linked terrestrial environs is prioritised to promote this overall land–ocean 'scape' ― a multi-realm *'ecoscape'* [@wedding2025bla].

::::{.column-margin}
::: {.callout-note #nte-cost title='Terrestrial and freshwater overlap'}
Wetlands provide an interesting case of overlap in the terrestrial and freshwater realms. Many species directly use both of 'realms'. The terrestrial plan accounts for this overlap through its incorporation freshwater features, that is, 'freshwater' associated species, and freshwater bodies [@escott2016dkn; @lotter2015trf]. The terrestrial plan is however specifically engineered to address terrestrial-focused conservation problems necessitating a separate exercise to address freshwater conservation planning.
:::
::::

The above linking from marine, estuary, freshwater to terrestrial, describes the hierarchical approach recommended for integrating biodiversity plans [@escott2016dkn; @lotter2015trf]. This 'linking' is done from the most dependant, that is, most affected by other adjacent realms, to the least-dependent realm. In conservation planning, the terrestrial realm is considered the least dependent, compared with the marine and estuarine realms, in KwaZulu-Natal [@escott2016dkn; @desmet2019ecb]. 

Overlap between realms has to be dealt with systematically. For conservation planning in KwaZulu-Natal, the rugged topography with incised valleys and associated catchment systems is best addressed through a catchment management approach [@escott2016dkn; @desmet2019ecb]. This catchment management system neatly ties the terrestrial to the estuarine, coastal and marine realms.

## Notes

### Eastern Cape BP integration of biodiversity realms

The following is taken/summarisied from the EC biodiversity plan (pg 5 of @desmet2019ecb). This is a description of their BP:  

1. Estuary CBA classification based on 2018 NBA.
1. Integrate estuary priorities into the freshwater Marxan cost layer.
1. Freshwater Marxan analysis (PUs = sub quarternary).
1. Extract selected PUs from freshwater Marxan analysis.
1. Add to these PUs NFEPA SQ4 fish sanctuaries, free flowing and flagship river
catchments.
1. Add freshwater features based on CBA criteria (i.e. wetlands and strategic water source areas,
Section 9).
1. Integrate freshwater priorities into terrestrial Marxan cost layer (Section 11.2).
1. Conduct terrestrial Marxan analysis.
1. Add terrestrial features based on CBA criteria.

Areas selected through the MARXAN analysis aimed to select enough sites to achieve representation
targets for vegetation types, species of conservation concern and expert mapped areas important
for biodiversity.  
Areas already identified as CBAs in existing plans and incorporated as is into the EC plan include:  
a. Estuary – All estuaries except those mapped by this project.  
b. Fresh water – NFEPA fish sanctuaries, Flagship Rivers and free flowing rivers.  
c. Terrestrial – none. CBAs in existing plan were integrated in to the Marxan cost layer.  
Entire mapped extent of features considered as being important for biodiversity pattern or process.
Inputs used to inform the Marxan cost layer. These features do not appear in the final CBA map.
They are use only to manipulate the cost layer to increase or decrease the likelihood of Marxan
selecting a site to achieve any given target.

<!-- 
::: {#fig-full_flow}

```{mermaid}

%% png: images/intro/fig03.png

flowchart TB

%% === Main stages ===
obj1[What & where]
obj2[Status assessment]
obj3[Representation & <br> persistence targets]
obj4[prioritisation analysis]

obj1 --> obj2
obj2 --> obj3
obj3 --> obj4


%% Feedback (use dashed; if not supported, we’ll restyle via linkStyle)
obj2 -.-> obj1
obj3 -.-> obj2
obj4 -.-> obj3


%% === Inputs to obj1 (What & where) ===
obj1_1([Ecosystem representation]) --> obj1
obj1_2([Refugia habitat & corridors]) --> obj1
obj1_3([Critical habitat features]) --> obj1
obj1_4([Species representation]) --> obj1
obj1_5(["Spatial avoidance (cost)"]) --> obj1


%% === Ecosystem representation details ===

obj1_1_1([Baseline ecosystem]) --> obj1_1_2([Landcover modification])
obj1_1_2 --> obj1_1_3([Ecosystem modification])
obj1_1_3 --> obj1_1_4([Development sprawl])
obj1_1_4 --> obj1_1_5(["Fragmentation & connectivity"])
obj1_1_6(["Climate refugia (& scenarios)"])--> obj1_1_5

%% Link ecosystem detail back up
obj1_1_2 --> obj1_1
obj1_1_5 --> obj1_2
obj1_1_6 --> obj1_2

%% Optional grey-ish relation represented as dashed
obj1_1_2 -.-> obj1_5

%% === Species representation details ===
obj1_4_1([Point locality data]) --> obj1_4_2([Species Distribution Models])
obj1_4_1 --> obj1_4
obj1_4_2 --> obj1_4

%% Bidirectional link: SDMs <-> Climate refugia
obj1_4_2 --> obj1_1_6
obj1_1_6 --> obj1_4_2

%% === Status assessment inputs ===
obj2_1([National & international risk status]) --> obj2
obj2_2([Provincial risk status]) --> obj2

%% === Targets inputs ===
obj3_1([National & international targets]) --> obj3
obj3_2([Provincial targets]) --> obj3
```

::: -->