---
title: Priotitization analyses
title-block-banner: true
bibliography: /home/paulg/refs/bspi.bib
---

# Analysis framework and software

To find the best working solution to the KZN Conservation Plan the @coreteam2025rv4 *prioritizR* package [@hanson2025scp] was used. There are a number of advantages to this approach. Unlike simulated annealing (e.g., Marxan), where *near*-optimal solutions are obtained through multiple runs, *prioritizR* uses mixed-integer linear programming, in a single run, to solve for _the_ optimal solution (@nte-marxan). The formulation how 'cost' is balanced across a landscape to delineate space for biodiversity (or other) features, that is, the 'conservation problem', is highly customisable using the *prioritizr* framework. As such, planners can explicitly control many conservation-problem parameters. Running a single run, versus multiple, to find the optimal solution speeds up complex problem-solving substantially.

::::{.column-margin}
::: {.callout-note #nte-marxan title='PrioritizR–Marxan integration'}
PrioritizR was set up to compare and run Marxan simulations. For a Marxan run prioritizR will accept Marxan formatted data and perform a Marxan run simulation. This means that preparation of data for prioritizR can be the same as for a Marxan run making integration, comparison, and movement between these planning tools seamless.
:::
::::

Some of this complexity in *prioritizR* conservation-problem solving includes advanced methods for zoning, and landscape connectivity and patch size [@hanson2025scp]. The *prioritizR* package integrates with @coreteam2025rv4 GIS environments enabling open source data pipeline development for conservation planning.

PrioritizR has had a broad uptake and is helping solve conservation problems; some interesting examples include:

- European terrestrial realm priority areas for 10‒30% protection scenarios [@visconti2024ati],
- National government marine biodiversity in Mozambique [@jones2021spa],
- Freshwater catchment and biodiversity conservation in Canada [@southee2021fcp],
- Marine genetic diversity (and socio-economic scenarios) in South Africa (West Coast) [@nielsen2023iee],
- Climate resilience on South Africa's West Coast [@nielsen2023iee],
- Functional and taxonomic diversity conservation planning in China's terrestrial realm (national) [@liu2026imb], and
- Restoration in the Brazilian Cerrado [@aragao2026oro].

## The conservation problem

The 'conservation problem' in *prioritizr* is resolved as a function of the following [@hanson2025scp],

$$problem = f(objectives + targets + constraints + penalties),$$

where

- **objectives** are the overall goals of the conservation planning exercise.

  - Conventionally, the 'min set' objective is aimed for whereby enough habitat for all species is sought at minimum cost.
  - Custom objectives can be set and compared.

- **targets** set the minimum proportion or amount of each feature's spatial distribution that should ideally be protected.

- **constraints** *forbid* solutions that either exhibit or do not exhibit a particular characteristic.

  - For example, 'lock in' or 'lock out' specific planning units to a zone, e.g., 'irreplaceable'.
  - The contiguity of planning units can also be set to determine connectivity and patch size trade-offs. This can be achieved per feature.
  - Planning units can be constrained to a particular zone, e.g., restoration, or low utilisation.

- **penalties** function to *limit* or *penalise* solutions that do not meet a specific characteristic.

  - For example, favour clumping to produce contiguous areas, or
  - reduce spatial fragmentation.

```{r prioritizr}
pkgs <- c("prioritizr")
to_install <- pkgs[!pkgs %in% installed.packages()[, "Package"]]
if (length(to_install) > 0) install.packages(to_install)

lapply(pkgs, library, character.only = TRUE)
```