---
# about section of the website. section contains general acknowledgements.
title: "Systematic Conservation Planning <br/> in KwaZulu-Natal"
abstract: The KwaZulu-Natal conservation plan is produced and maintained by Ezemvelo KwaZulu-Natal Wildlife in collaboration with many partners. This plan serves as the guidelines for protected area expansion, and a spatial framework for recommended land-use activities, to promote the persistence of biodiversity, associated ecosystem functioning, and linked cultural sites, that the people of KwaZulu-Natal are in community with.
---

# KZN biodiversity

What's special about KZN biodiversity?

  - Description of KZN taxa and their diversity + endemism.
  - Conservation status stats.
  - Land use stats and emerging threats.

# The planning community

The KwaZulu-Natal Systematic Conservation Plan has a legacy of robust science that is backed and built through community involvement. The Ezemvelo KZN Wildlife Conservation Plan Steering Committee ― that was established to guide the plan ― works with internal and external scientists to maintain and revise the Conservation Plan. Input from partners, to ensure the plan is aligned to provincial and national objectives is essential.

  - Table of partners/stakeholders/contributors.
  - Contributing authors should be cited per section/page.


```{r}
#| echo: false
#| label: partners

# see the parnerships csv for adding acknowledgements
```


