---
title: "Ecosystem representation"
abstract:
    The ecosystem coverage selected for the KwaZulu-Natal Systematic Conservation Plan has been developed over many decades using the acute knowledge of Ezemvelo specialist scientists. 

author:
    - name: Debbie Jewitt
      orcid: "0000-0002-0580-3107"
      affiliations:
        id: cra
        name: Biodiversity, Spatial Planning and Information, Ezemvelo KZN Wildlife
    - name: Felicity Elliot
      affiliations:
        ref: bspi
    - name: Shannon Rushworth
      affiliations:
        ref: bspi
    - name: Andy Blackmore
      affiliations:
        id: iem
        name: Integrated Environmental Management & Protected Area Planning, Ezemvelo KZN Wildlife
    - name: Craig Mulqueeny
      affiliations:
        id: ss
        name: Scientific Services, Ezemvelo KZN Wildlife
    - name: Ian Rushworth
      affiliations:
        ref: ss
    - name: Adrian Armstrong
      affiliations:
        id: cra
        name: Scientific Services, Conservation and Research, Ezemvelo KZN Wildlife
    - name: Clinton Carbutt
      affiliations:
        ref: cra
    - name: Brent Coverdale
      affiliations:
        ref: cra
    - name: Debbie Jewitt
      affiliations:
        ref: cra
    - name: Skhumuzo Khubeka
      affiliations:
        ref: cra


title-block-banner: true
bibliography: /home/paulg/refs/bspi.bib

execute: 
  warning: false
  message: false

# DOCX:
# To convert to word run the build word script
# cd website
# . scripts/build_word.sh
---

## Ecosystem representation {#sec-eco-rep}

Incorporating ecosystem types in the conservation planning process serves to broadly capture the spatial distribution of distinct-biological communities, and associated species diversity, that is, the gamma diversity [@whittaker1960vot] across the region of interest [@mucina2024evb]. Following the previous terrestrial SCP for KwaZulu-Natal [@escott2010cpw], a vegetation-type map formed a robust surrogate for ecosystem types. Vegetation types commonly serve as surrogates for ecosystem types because they largely capture differences in biodiversity patterns across the landscape [@sanbi2024mbp].

For an up-to-date representation of ecosystem extent, the provincial-vegetation map (i.e., coverage) had to be adjusted. The provincial-vegetation coverage serves as a representation of “natural” vegetation communities prior to global change pressures ca. 1750 [@mucina2018tvm]. Therefore, the coverage had to be adjusted to reflect the current state of ecosystems using the best available data.
