---
id: intro
title: "Introduction"
abstract:
    The three principal questions that guide the Ezemvelo KZN Wildlife Systematic Conservation Plan, are; 1) What biodiversity does the province contain and where is it, 2) what is the status of this biodiversity, and 3) addressed by a prioritisation analysis --- where and how should conservation efforts be prioritized. This technical introduction elaborates on each of these questions that are expanded into five stages, each critical for a detailed understanding of the conservation plan's associated products.

author:
    - name: Paul Gordijn
      orcid: "0000-0002-0580-3107"
      affiliations:
        id: bspi
        name: Biodiversity, Spatial Planning and Information, Ezemvelo KZN Wildlife
    - name: Felicity Elliot
      affiliations:
        ref: bspi
    - name: Shannon Rushworth
      affiliations:
        ref: bspi
    - name: Andy Blackmore
      affiliations:
        id: iem
        name: Integrated Environmental Management & Protected Area Planning, Ezemvelo KZN Wildlife
    - name: Craig Mulqueeny
      affiliations:
        id: ss
        name: Scientific Services, Ezemvelo KZN Wildlife
    - name: Ian Rushworth
      affiliations:
        ref: ss
    - name: Adrian Armstrong
      affiliations:
        id: cra
        name: Scientific Services, Conservation and Research, Ezemvelo KZN Wildlife
    - name: Clinton Carbutt
      affiliations:
        ref: cra
    - name: Brent Coverdale
      affiliations:
        ref: cra
    - name: Debbie Jewitt
      affiliations:
        ref: cra
    - name: Skhumuzo Khubeka
      affiliations:
        ref: cra


title-block-banner: true
bibliography: /home/paulg/refs/bspi.bib

execute: 
  warning: false
  message: false

# DOCX:
# To convert to word run the build word script
# cd website
# . scripts/build_word.sh
---

[Download Word (docx)](intro.docx){.btn .btn-secondary}

# The KwaZulu-Natal Systematic Conservation Plan {#sec-updated-scp}

## The Plan objective



The Systematic Conservation Plan (SCP) around these key questions [@sanbi2024mbp; @jung2025aia]:

1. What biodiversity and where is it?
2. What is the state of this biodiversity?
3. Where and how should conservation efforts be prioritised?

These questions form the basis for the structure of this conservation plan. The first key question involves collation and modelling of data in order to obtain the best available spatial representation of biodiversity. The second is largely concerned with the conservation or risk status of biodiversity that will guide the mapping of biodiversity, and the prioritisation analyses in point three.

# Conservation plan stages {#sec-stages}

The main stages of the conservation plan are depicted in @fig-flow_main below.

::: {#fig-flow_main}

```{mermaid}
%%| fig-align: center

%% png: images/intro/fig01.png

flowchart TD

%% === Main stages ===
obj1([What & where])
obj2([Status assessment])
obj3([Representation & <br> persistence targets])
obj4([prioritisation analysis])
obj5([Product development])

obj1 --> obj2
obj2 --> obj3
obj3 --> obj4
obj4 --> obj5


%% Feedback (use dashed; if not supported, we’ll restyle via linkStyle)
obj2 -.-> obj1
obj3 -.-> obj2
obj4 -.-> obj3
obj5 -.-> obj4
```

Flowchart depicting the iterative stages of gathering data, analyses, and outputs of the systematic conservation plan (c.f. @sanbi2024mbp).

:::

The stages^[These translate to the plan's objectives] of this SCP are as follows:

1. **The what and where of biodiversity — feature representation** (see ATsec-eco-state):

    a. Develop a baseline‑ecosystem layer that broadly represents the spatial distribution of biotic communities (i.e., coarse‑filter features).

    a. Determine the state of ecosystems and their biodiversity:

        i. Ascertain the distribution of protected and conserved areas.
        i. Refine the baseline‑ecosystems layer to represent the current state of biodiversity.

    a. Bolster the representation of all species.^[We use “species” in the broad sense, referring to any distinct taxonomic unit (e.g., subspecies) unless otherwise indicated.]

    a. Represent ecosystem function and change — collection of additional spatial datasets.^[If available, these data can be considered for inclusion in prioritisation analysis and assessment.]

        i. Ecosystem processes  
        i. Ecosystem infrastructure  
        i. Ecosystem services  
        i. Ecological condition  
        i. Climate change information  
        i. Socio‑economic data  

1. **Determine the current state of ecosystems and their biodiversity:**

    a. Evaluate the risk and protection status of ecosystems.
    a. Align and compare provincial (and where appropriate trans‑regional) ecosystem risk status.
    a. Evaluate the risk and protection status of species.

1. **Set representation and persistence targets:**

    a. Representation and persistence of ecosystems, including alignment with the Global Biodiversity Framework [@cbd2022kmg].
    a. Representation and persistence of species.

4. **Spatial prioritisation:**

    a. Spatial framework of evaluation --- planning units.
    a. Compilation of cost (decision‑support) layers.
    a. Systematic spatial prioritisation analyses and scenario modelling.
    a. Sensitivity analysis.

5. **Product development.**

# Integration of biodiversity realms

Insuring integration of the marine, estuarine, freshwater and terrestrial biodiversity realms is critical for a connected landscape to seascape scape approach. This integration ensures that critical marine realms are supported by important estuaries. These estuaries are maintained through a freshwater plan, and conservation in linked terrestrial environs is prioritised to support this overall land–ocean 'scape' ― a multi-realm 'ecoscape' [@wedding2025bla].

## What & where

::: {#fig-what_where}


```{mermaid}
%%| fig-align: center

%% png: images/intro/fig02.png

flowchart TD

%% === Main stages ===
obj1[What & where]
%%obj2([Status assessment])
%%obj3([Representation & <br> persistence targets])
%%obj4([prioritisation analysis])
%%obj5([Product development])

%%obj1 --> obj2
%%obj2 --> obj3
%%obj3 --> obj4
%%obj4 --> obj5


%% Feedback (use dashed; if not supported, we’ll restyle via linkStyle)
%%obj2 -.-> obj1
%%obj3 -.-> obj2
%%obj4 -.-> obj3
%%obj5 -.-> obj4

%% === Inputs to obj1 (What & where) ===
obj1_1([Ecosystem representation]) --> obj1
obj1_2([Refugia habitat & corridors]) --> obj1
obj1_3([Critical habitat features]) --> obj1
obj1_4([Species representation]) --> obj1
obj1_5(["Spatial avoidance (cost)"]) --> obj1

%% === Ecosystem representation details ===

obj1_1_1([Baseline ecosystem]) --> obj1_1_2([Landcover modification])
obj1_1_2 --> obj1_1_3([Ecosystem modification])
obj1_1_3 --> obj1_1_4([Development sprawl])
obj1_1_4 --> obj1_1_5(["Fragmentation & connectivity"])
obj1_1_6(["Climate refugia (& scenarios)"])--> obj1_1_5

%% Link ecosystem detail back up
obj1_1_2 --> obj1_1
obj1_1_5 --> obj1_2
obj1_1_6 --> obj1_2

%% Optional grey-ish relation represented as dashed
obj1_1_2 -.-> obj1_5

%% === Species representation details ===
obj1_4_1([Point locality data]) --> obj1_4_2([Species Distribution Models])
obj1_4_1 --> obj1_4
obj1_4_2 --> obj1_4

%% Bidirectional link: SDMs <-> Climate refugia
obj1_4_2 --> obj1_1_6
obj1_1_6 --> obj1_4_2
```

Inputs to determining the what and where of biodiversity.

:::


# The what and where of biodiversity {#chap-ecosys-layer}

For robust representation of biodiversity and associated ecosystem infrastructure and services into the future, the what and where of biodiversity needs to consider change drivers. The functions of biodiversity, and associated ecosystems, also need to be considered for accurate representation when attempting to ensure conservation of these features.

In order to maximise representation of biodiversity in a landscape, the **SCP** process adopts a two-pronged approach, specifically:

1) a **wide-ranging** (or coarse-filter): “Ecosystem representation” approach (see [Section @sec-eco-rep]), and  
2) a **targeted** (or fine-filter): “Species representation” approach (see [Species](species.qmd)) [@sanbi2024mbp].

Representation of the ecosystem types in the area-of-interest largely fulfils the **wide-ranging** component, that is, if the SCP incorporates the full diversity of ecosystems, it is likely to represent their constituent taxa. The complementary approach, that is, the **targeted** approach, caters for specific, threatened taxa, or those not operating within the parameters of represented ecosystems [@margules2000scp].

## Ecosystem representation {#sec-eco-rep}

Incorporating ecosystem types in the SCP process serves to broadly capture the spatial distribution of distinct-biological communities, and thereby the full suite of species—i.e., gamma diversity [@whittaker1960vot]—across the region of interest [@mucina2024evb]. Following the previous terrestrial SCP for KwaZulu-Natal [@escott2010cpw], a vegetation-type map formed a robust surrogate for ecosystem types. Vegetation types commonly serve as surrogates for ecosystem types because they largely capture differences in biodiversity patterns across the landscape [@sanbi2024mbp].

For an up-to-date representation of ecosystem extent, the provincial-vegetation map (i.e., coverage) had to be adjusted. The provincial-vegetation coverage serves as a representation of “natural” vegetation communities prior to **GC** pressures ca. 1750 [@mucina2018tvm]. Therefore, the coverage had to be adjusted to reflect the current state of ecosystems using the best available data.

<!-- More info to follow here as the Vegetation Map technical working group gets under way. -->

### Ecosystem and biodiversity state datasets {#sec-eco-state}

#### Protected and conserved ecosystems

#### Ecosystem protection and conservation



::: {#fig-full_flow}

```{mermaid}

%% png: images/intro/fig03.png

flowchart TB

%% === Main stages ===
obj1[What & where]
obj2[Status assessment]
obj3[Representation & <br> persistence targets]
obj4[prioritisation analysis]

obj1 --> obj2
obj2 --> obj3
obj3 --> obj4


%% Feedback (use dashed; if not supported, we’ll restyle via linkStyle)
obj2 -.-> obj1
obj3 -.-> obj2
obj4 -.-> obj3


%% === Inputs to obj1 (What & where) ===
obj1_1([Ecosystem representation]) --> obj1
obj1_2([Refugia habitat & corridors]) --> obj1
obj1_3([Critical habitat features]) --> obj1
obj1_4([Species representation]) --> obj1
obj1_5(["Spatial avoidance (cost)"]) --> obj1


%% === Ecosystem representation details ===

obj1_1_1([Baseline ecosystem]) --> obj1_1_2([Landcover modification])
obj1_1_2 --> obj1_1_3([Ecosystem modification])
obj1_1_3 --> obj1_1_4([Development sprawl])
obj1_1_4 --> obj1_1_5(["Fragmentation & connectivity"])
obj1_1_6(["Climate refugia (& scenarios)"])--> obj1_1_5

%% Link ecosystem detail back up
obj1_1_2 --> obj1_1
obj1_1_5 --> obj1_2
obj1_1_6 --> obj1_2

%% Optional grey-ish relation represented as dashed
obj1_1_2 -.-> obj1_5

%% === Species representation details ===
obj1_4_1([Point locality data]) --> obj1_4_2([Species Distribution Models])
obj1_4_1 --> obj1_4
obj1_4_2 --> obj1_4

%% Bidirectional link: SDMs <-> Climate refugia
obj1_4_2 --> obj1_1_6
obj1_1_6 --> obj1_4_2

%% === Status assessment inputs ===
obj2_1([National & international risk status]) --> obj2
obj2_2([Provincial risk status]) --> obj2

%% === Targets inputs ===
obj3_1([National & international targets]) --> obj3
obj3_2([Provincial targets]) --> obj3
```

:::